config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'about#main'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"
  put "/blog_images" => "blog_images#create" #for file-upload on posts#edit
  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  match 'update_avatar' => 'users#update_avatar', :as => :update_avatar
  match "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  match 'update_poster/:course_id' => 'courses#update_poster', :as => :update_poster

  resources :comments
  match "/comment_preview" => "comments#preview", :as => "comment_preview"

  match "login" => "info#marketing", :as => "login"
  match "submit_login_form" => "users#login"
  match "logout" => "users#logout", :as => "logout"
  match "signup" => "users#signup", :as => "signup"

  put "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/member" => "users#index", :as => "user_index"
  post "/member" => "users#create"
  put "/crop" => "users#crop", :as => "crop"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  put "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name/edit" => "courses#edit" , :as => "edit_course"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  get "/:member_name/:course_name/:position/edit" => "courses#edit_video"
  match "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :video_id, :user_id
  belongs_to :user
  belongs_to :video

  after_create :send_notification_to_commenters

  private
  def here_users
    all = []
    self.video.comments.each do |c|
      all << c.user
    end
    all << self.video.user
    all.uniq
  end
  def send_notification_to_commenters
    here_users.each do |u|
      Notification.notify(u, self, self.user, "comment") unless u.id == self.user.id
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def new
    @comment = Comment.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = current_user.comments.build(params[:comment])
    @comment.save
    respond_to do |format|
      format.html do
        if @comment.errors.present?
          redirect_to_target_or_default root_url
        else
          redirect_to_target_or_default root_url
        end
      end
      format.js
    end
  end

  def preview
    @content = params[:content]
    respond_to do |format|
      format.js
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to_target_or_default root_url, notice: 'comment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    destroy_notifications @comment
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to_target_or_default root_url }
      format.js
    end
  end
end

app/views/comments/_comment.html.erb
<div class="bubble">
  <%= div_for comment do %>
    <div class="comment-header">
      <i class="icon-comment"></i>
      <%= link_to comment.user.name, member_path(comment.user.name), :class => "comment-header-author" %>
      <%= link_to "说", video_comment_path(comment.id) %>
      <span class="comment-header-right">
        <span class="comment-header-date">
          <%= time_ago_in_words comment.created_at %>前
        </span>
        <% if current_user.try(:id) == comment.user.id %>
          <ul class="comment-header-actions">
            <li><%= link_to t("edit"), edit_comment_path(comment), :remote => true %></li>
            <li><%= link_to t("delete"), comment, :confirm => t('confirm_delete'), :method => :delete, :remote => true %></li>
          </ul>
        <% end %>
      </span>
    </div>
    <div class="comment-content ">
      <div class="edit-comment-hide">
        <div class="comment-body markdown-format">
          <%= markdown comment.content %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="form-content">
 <%= form_for @comment, :remote => true do |f| %>
    <%= f.text_area :content %>
    <%= f.submit t("update_comment"), :class=>"btn", :remote => true, :id => "comment_btn" %>
  <% end %>
</div>

app/views/comments/_new_comment_form.html.erb
<%= content_for :template_js do %>
  <script>
    $("#comment-btn").click(function() {
      if ($.trim($('.new-comment-content textarea').val()) == "")
      {
        $('.new-comment-content .error').show();
        return false;
      }
    });
  </script>
<% end %>
<div class="bubble">
  <div class="bubble-inner">
    <div class="previewable-comment-form">
      <div class="comment-form-head tabnav">
        <ul class="tabnav-tabs">
          <li><a href="#" class="tabnav-tab write-tab selected"><%= t('edit') %></a></li>
          <li><%= link_to t('preview'), "#" , :class => "tabnav-tab preview-tab" %></li>
        </ul>
      </div>
      <div class="comment-content new-comment-content clearfix">
        <div class="error" style="display: none;">
          <%= t('error_blank_content') %>
        </div>
        <%= form_for(Comment.new(:video_id => @video.id, :user_id => current_user.id), :remote => true) do |f| %>
          <%= f.hidden_field :video_id %>
          <%= f.hidden_field :user_id  %>
          <%= f.text_area :content %>
          <br>
          <%= f.submit "#{t('publish_comment')}", :class => "btn btn-success", :id => "comment-btn", :disable_with => "sending..." %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$('#comments').append("<%= escape_javascript render @comment %>");
$('#new_comment textarea').val("");
$('#preview-box').empty();

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").parent().remove();

app/views/comments/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/comments/edit.js.erb
$("#<%= dom_id(@comment) %> .edit-comment-hide").replaceWith("<%= escape_javascript render('form') %>");

app/views/comments/index.html.erb
<div class="container">
  <h1>All comments</h1>
  <% @comments.each do |comment| %>
    <div class="box">
      <%= comment.content %>
    </div>
  <% end %>
</div>

app/views/comments/preview.js.erb
$(".preview-box").html("<%= escape_javascript markdown @content %>");

app/views/comments/update.js.erb
<% if @comment.errors.present? %>
  $("#<%= dom_id(@comment) %>").find("form").prepend("<div id=\"error\">Error!</div>");
<% else %>
  $("#<%= dom_id(@comment) %>").parent().replaceWith("<%= escape_javascript render @comment %> ");
<% end %>