config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'about#main'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"
  put "/blog_images" => "blog_images#create" #for file-upload on posts#edit
  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  match 'update_avatar' => 'users#update_avatar', :as => :update_avatar
  match "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  match 'update_poster/:course_id' => 'courses#update_poster', :as => :update_poster

  resources :comments
  match "/comment_preview" => "comments#preview", :as => "comment_preview"

  match "login" => "info#marketing", :as => "login"
  match "submit_login_form" => "users#login"
  match "logout" => "users#logout", :as => "logout"
  match "signup" => "users#signup", :as => "signup"

  put "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/member" => "users#index", :as => "user_index"
  post "/member" => "users#create"
  put "/crop" => "users#crop", :as => "crop"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  put "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name/edit" => "courses#edit" , :as => "edit_course"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  get "/:member_name/:course_name/:position/edit" => "courses#edit_video"
  match "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :executor, :class_name => 'User'
  belongs_to :notifiable, :polymorphic => true
  scope :recent, order("created_at DESC")

  attr_accessible :action, :unread, :notifiable, :user, :executor

  def self.notify(user, notifiable, executor, unread = true, action)
    n = Notification.new user: user, notifiable: notifiable
    n.action = action
    n.unread = unread
    n.executor = executor
    n.save
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  after_filter :mark_read, :only => :index

  def index
    @notifications = current_user.notifications.recent
  end
  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_path }
    end
  end
  def clear
    current_user.notifications.delete_all
    respond_to do |format|
      format.html { redirect_to notifications_path }
    end
  end
  def mark_read
    current_user.notifications.update_all(unread: false)
  end
end

app/views/notifications/_notification_activity.html.erb
<% activity = notification.notifiable %>
<% action = notification.notifiable.action%>
<% case action %>
<% when "destroy" %>
<td class="notificon">
  <i class="icon-trash icon-2x"></i>
  <%= render :partial => "notification_executor", :locals => { :notification => notification} %>
  <span class="annotate"> 删除了一个视频</span>
</td>
<% when "create", "update" %>
  <% if activity.trackable.present? %>
    <td class="notificon">
      <i class="icon-<%= action == "create" ? "plus-sign" : "refresh" %> icon-2x"></i>
    </td>
    <td>
      <%= render :partial => "notification_executor", :locals => { :notification => notification} %>
      <% if action == "create" %>
        <span class="annotate"> 上传一个新视频： </span>
      <% else %>
        <span class="annotate"> 更新了视频： </span>
      <% end %>
      <%= video_course_path(activity.trackable) %>
    </td>
  <% end %>
<% end %>

app/views/notifications/_notification_comment.html.erb
<% comment = notification.notifiable %>
<% case notification.action %>
<% when "comment" %>
  <td class="notificon"><i class="icon-comments icon-2x"></i></td>
  <td>
    <%= render :partial => "notification_executor", :locals => { :notification => notification } %>
    <span class="annotate">回复了你评论过的课程章节: </span>
    <%= link_to comment.video.title, video_comment_path(comment.id) %>
    <%- if comment.present? -%>
      <div class="comment-body markdown-format">
        <%= markdown comment.content %>
      </div>
    <%- end -%>
  </td>
<% end %>

app/views/notifications/_notification_course.html.erb
<% case notification.action %>
<% when "watch" %>
  <td class="notificon"><i class="icon-eye-open icon-2x"></i></td>
  <td>
    <%= render :partial => "notification_executor", :locals => { :notification => notification } %>

    <% course = notification.notifiable %>
    <span class="annotate">关注了你的课程: </span>
    <%= link_to course.name, course_path(course) %>
  </td>
<% end %>

app/views/notifications/_notification_executor.html.erb
<% executor = notification.executor %>
<%= link_to member_path(executor.name) do %>
  <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
<% end %>
<%= link_to member_path(executor.name) do %>
  <span><%= executor.name %></span>
<% end %>
<% if notification.notifiable_type == "Activity" %>
  <span class="annotate">为你关注的课程： </span>
  <%= course_name_tag(notification.notifiable.course_id) %>
<% end %>

app/views/notifications/index.html.erb
<div id="notifications">
  <div class="container details">
    <div class="title">
      <div class="clear-all">
        <%= link_to "清空", clear_notifications_path, :method => "delete", :class => "minibutton danger" %>
      </div>
      <div class="total">通知提醒<small> (<%= @notifications.count  %> 条)</small></div>
    </div>
    <% if @notifications.blank? %>
      <div class="no-content">
        暂无通知
      </div>
    <% else %>
      <table class="content">
        <tbody>
          <% for notification in @notifications %>
              <% type = notification.notifiable_type.underscore %>
              <tr <%= "class=highlight" if notification.unread %>>
                <%= render :partial => "notification_#{type}", :locals => { :notification => notification }%>
                <td><%= time_ago_in_words notification.created_at %>前</td>
                <td class="last"><%= link_to "删除", notification_path(notification), :method => "delete", :class => "minibuton danger" %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>