config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'about#main'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"
  put "/blog_images" => "blog_images#create" #for file-upload on posts#edit
  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  match 'update_avatar' => 'users#update_avatar', :as => :update_avatar
  match "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  match 'update_poster/:course_id' => 'courses#update_poster', :as => :update_poster

  resources :comments
  match "/comment_preview" => "comments#preview", :as => "comment_preview"

  match "login" => "info#marketing", :as => "login"
  match "submit_login_form" => "users#login"
  match "logout" => "users#logout", :as => "logout"
  match "signup" => "users#signup", :as => "signup"

  put "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/member" => "users#index", :as => "user_index"
  post "/member" => "users#create"
  put "/crop" => "users#crop", :as => "crop"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  put "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name/edit" => "courses#edit" , :as => "edit_course"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  get "/:member_name/:course_name/:position/edit" => "courses#edit_video"
  match "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/controllers/courses_controller.rb
# encoding: utf-8
class CoursesController < ApplicationController
  before_filter :check_owner, :only => [:edit, :update, :destory]
  before_filter :find_course, :only => [:show, :edit, :watch, :unwatch, :watchers]

  def check_owner
    if current_user.nil?
      redirect_to :root, :notice => t('login_first_plz')
      return
    end
    if params[:course_name]
      user = User.find_by_name(params[:member_name])
      course = Course.where(:user_id => user.id, :name => params[:course_name]).first
    else
      # for update
      course = Course.where(:user_id => params[:course][:user_id], :name => params[:course][:name]).first
    end
    if course.user != current_user
      redirect_to :root, :notice => "抱歉，只有课程所有者才有此权限"
      return
    end
  end

  def new
    @course = Course.new(:user_id => current_user.id)
    session[:return_to] = request.url
  end

  def index
    @courses = Course.where(public: true).reverse
    @course_groups = []
    @courses.each_index do |i|
      if i%3 == 0
        @course_groups << @courses[i..i+2]
      end
    end
  end

  def show
    if @course.nil?
      redirect_to(:root, :notice => '抱歉，您访问的课程不存在')
    else
      if params[:position].present?
        @video = Video.where(:course_id => @course.id,:position => params[:position].to_i).first
      elsif @course.videos.empty?
        @video = nil
      else
        @video = Video.where(:course_id => @course.id,:position => 1).first
      end
      session[:return_to] = request.url
    end
  end

  def edit
    session[:return_to] = request.url
  end

  def update
    if params[:course][:public]
      Course.update_all("public=1, public=0")
    end
    @course = Course.where(:user_id => params[:course][:user_id], :name => params[:course][:name]).first
    @course.update_attributes(params[:course])
    @course.name = PinYin.of_string(params[:course][:title]).join('-').downcase
    print params[:course][:public]
    respond_to do |format|
      if @course.save
        format.html { redirect_to course_path(@course), :success => 'Course was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def edit_video
    respond_to do |format|
      format.js {
        user = User.find_by_name(params[:member_name])
        course = Course.where(:user_id => user.id, :name => params[:course_name]).first
        @video = Video.where(:course_id => course.id, :position => params[:position]).first
      }
    end
  end

  def update_poster
    @course = Course.find(params[:course_id])
    respond_to do |format|
      format.js do
        @course.update_attributes(params[:course])
      end
    end
  end

  def create
    user = User.find(params[:course][:user_id])
    title = params[:course][:title]
    name = PinYin.of_string(title).join('-').downcase
    user.courses.each do |c|
      if c.name == name
        @name_exsits = true
      end
    end
    if defined? @name_exsits
      redirect_to_target_or_default :root, :notice => "你已经创建了这门课程"
      return
    end
    course = Course.new(params[:course])
    course.name = name
    if course.save
      track_activity course, course.id
      redirect_to edit_course_path(course), :notice => "新课程创建成功！"
    else
      redirect_to_target_or_default :root, :notice => "新课程创建失败！"
    end
  end

  def destroy
    user = User.find_by_name(params[:member_name])
    course = Course.where(:user_id => user.id, :name => params[:course_name]).first
    course.destroy
    redirect_to member_path(user.name)
  end

  def watch
    @course.add_watcher(current_user)
    Notification.notify @course.user, @course, current_user, "watch"
    render :text => "1"
  end

  def unwatch
    @course.delete_watcher(current_user)
    render :text => "1"
  end

  def watchers
    @watchers = @course.watchers
  end

  private
  def find_course
    user = User.find_by_name(params[:member_name])
    @course = Course.where(:user_id => user.id, :name => params[:course_name]).first
  end
end

app/helpers/courses_helper.rb
# encoding: utf-8
module CoursesHelper
  def course_watch_tag(course)
    return "" if course.blank?
    return "" if owner?(course)
    class_name = "watch"
    text = t('watch_course')
    if current_user.blank?
      title = "您必须登录后才能关注课程"
      return link_to text, login_url, :class => "minibutton with-count", :title => title, :rel => "twipsy"
    end
    if course.watchers.include?(current_user)
      class_name = "watched"
      text = t('unwatch_course')
    end
    link_to text, "#", :onclick => "return Courses.watch(this);",
            :class => "minibutton with-count",
            'data-user' => course.user.name,
            'data-course' => course.name,
            'data-watched' => (class_name == "watched")
  end
end

app/views/courses/_ad.html.erb
<div class="course-thumb"> 
  
  <%= link_to course_path(course), :class => "course-detail green-box-shadow" do %>
  <%= image_tag course.poster_url, :id => 'adpost'%>
    <div class="course-info">
      <h4>
        <%= course.title %>
        <% if !course.public %>
          <span class="private-label"><%= t('course_private') %></span>
        <% end %>
      </h4>
      <p><%= course.description %></p>
    </div>
  <% end %>
  
  <div class="course-author">
    <%= link_to course.user.name, member_path(course.user.name) %>
  </div>

  <% if current_user && current_user == course.user %>
    <ul class="course-actions">
      <li><%= link_to t('edit'), edit_course_path(course) %></li>
      <li><%= link_to t('delete'), course, :confirm => t('confirm_delete'), :method => :delete %></li>
    </ul>
  <% end %>

</div>

app/views/courses/_add_photo.html.erb
<div class="rightbox">
  <div class="ad-image">
    <div id="uploadPreview">
        <%= image_tag course.poster_url , :id => 'poster'%>
      
    </div>
  </div>
  <div class="ad-title">
    <input class="inputBox titleB inputStyleB_orange" id="input_title2" name="" type="text" value=<%= course.title %> maxlength="10"  />
  </div>
  <div class="ad-content">
    <textarea id="input_content2"  value="" name="input_content2"  style="font-size:16px;"><%= course.description %></textarea> 
  </div>

</div>

app/views/courses/_add_video.html.erb
<% content_for :template_js do %>
  <%= javascript_include_tag 'i_fileupload'%>
  <script>
    jQuery(function($) {
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          formData: {course_id: <%= course.id %>},
          dataType: 'script',
          url: '/videos.js',
          add: function(e, data){
            types = /(\.|\/)(mov|mp4)$/i;
            file = data.files[0];
            if (types.test(file.type) || types.test(file.name))
            {
              $('#filesize').html("文件大小： " + "<span class='number'>" + (file.size/(1024*1024)).toFixed(2) + "</span>" + "M");
              file = data.files[0];
              data.context = $(tmpl("template-upload", file));
              $('.secondary-info').append(data.context);
              data.submit();
            }
            else
            {
              alert("上传失败：" + file.name + " 视频格式错误，请上传mov或mp4文件");
            }
          },
          start: function(e) {
            _tip.html('上传中&nbsp;&middot;&middot;&middot;');
            $('#submit_video_info').attr('value', '上传中...请稍等');
            $('#submit_video_info').attr('disabled', 'true');
            $('a.fileupload-btn').bind('click', false);
          },
          progress: function(e, data){
            if(data.context) {
              progress = parseInt(data.loaded / data.total * 100, 10);
              data.context.find('.bar').css('width', progress + '%');
              $('#progress-bar').html("<span class='progress-text'>" + progress + '%' + "</span>");
            }
          },
          done: function (e, data) {
            _tip.html("视频上传成功！");
          },
      });
    });
  </script>
<% end %>


<div class="add-video-box">
  <div class="secondary-info">
    <h1 id="upload-new-video"> <%= t('upload_new_video') %> </h1>
    <div id="filesize">
      <p><%= t('note_max_video_size_50m') %></p>
      <p><%= t('supported_video_format') %></p>
    </div>
    <a class= "fileupload-btn button">
      <span id="upload-tip"><%= t('click_to_upload_a_video') %></span>
      <input id="fileupload" name="video[asset]" type="file">
    </a>
    <script id="template-upload" type="text/x-tmpl">
      <div class="upload">
        {%=o.name%}
        <div class="progress">
          <div class="bar" id="progress-bar" style="width: 0%"></div>
        </div>
      </div>
    </script>
  </div>

  <div class="primary-info">
    <h1><%= t('enter_video_info') %></h1>
    <%= form_for(Video.new) do |f| %>
      <dl class="form">
        <dt>
          <%= f.label t("video_title") %>
        </dt>
        <dd>
          <%= f.text_field :title, :class => "short" %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
        <%= f.label t("video_desc") %>
        </dt>
        <dd>
        <%= f.text_area :desc, :size => "14x4", :id => "video_desc", :class => "short" %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
        <%= f.check_box :free %>
        <%= f.label t('free') %>
        </dt>
      </dl>
      <%= f.submit t('submit_video_info'), :class => "minibutton", :disabled => true, data: {disable_with: t('saving') + "..."}, :id => "submit_video_info" %>
    <% end %>
  </div>
</div>

app/views/courses/_all_added_videos.html.erb
<div class="playlist-container">
  <ul id="play-list" class="playlist" data-update-url="/sort_videos">
    <% course.videos.each do |video| %>
      <%= content_tag_for :li, video do %>
        <a class="video" href="<%= course_path(video.course) + '/' + video.position.to_s + '/edit.js'  %> " data-remote='true'>
          <div class="video-icon">
            <i class="icon-facetime-video"></i>
          </div>
          <span class="video-info">
            <%= video.title %>
            <%= "(free)" if video.free? %>
          </span>
        </a>
        <%= link_to t('delete'), video, :method =>"delete", :class => "delete-action", :confirm => t('confirm_delete') %>
      <% end %>
    <% end %>
  </ul>
</div>

<%= content_for :template_js do %>
  <script>
    jQuery(function() {
      return $('#play-list').sortable({
        axis: 'y',
        update: function() {
          $.post($(this).data('update-url'), $(this).sortable('serialize'));
          location.reload();// to update all the position value
        }
      });
    });
  </script>
<% end %>

app/views/courses/_course.html.erb
<div class="course-thumb"> 
  <%= link_to course_path(course), :class => "course-detail green-box-shadow" do %>
    <div class="poster-area" style="background-image: url(<%= course.poster_url %>);">
          </div>
    <div class="course-info">
      <h4>
        <%= course.title %>
        <% if !course.public %>
          <span class="private-label"><%= t('course_private') %></span>
        <% end %>
      </h4>
      <p><%= course.description %></p>
    </div>
  <% end %>
  <div class="course-author">
    <%= link_to course.user.name, member_path(course.user.name) %>
  </div>

  <% if current_user && current_user == course.user %>
    <ul class="course-actions">
      <li><%= link_to t('edit'), edit_course_path(course) %></li>
      <li><%= link_to t('delete'), course, :confirm => t('confirm_delete'), :method => :delete %></li>
    </ul>
  <% end %>
</div>

app/views/courses/_edit_video.html.erb
<script>
  jQuery(function($) {
    var _tip = $("#upload-tip");
    $('#fileupload').fileupload({
      url: '/update_video/<%= video.id %>',
      add: function(e, data){
        types = /(\.|\/)(mov|mp4)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name))
        {
          $('#filesize').html("文件大小： " + "<span class='number'>" + (file.size/(1024*1024)).toFixed(2) + "</span>" + "M");
          file = data.files[0];
          data.context = $(tmpl("template-upload", file));
          $('.secondary-info').append(data.context);
          data.submit();
        }
        else
        {
          alert("上传失败：" + file.name + " 视频格式错误，请上传mov或mp4文件");
        }
      },
      start: function(e) {
        _tip.html('上传中&nbsp;&middot;&middot;&middot;');
        $('#submit_video_info').attr('value', '上传中...请稍等');
        $('#submit_video_info').attr('disabled', 'true');
        $('a.fileupload-btn').bind('click', false);
      },
      progress: function(e, data){
        if(data.context) {
          progress = parseInt(data.loaded / data.total * 100, 10);
          data.context.find('.bar').css('width', progress + '%');
        }
      },
      done: function (e, data) {
        _tip.html("视频上传成功！");
        $('#submit_video_info').attr('value', '保存');
        $('#submit_video_info').removeAttr('disabled');
      },
    });
  });
</script>

<div class="add-video-box">
  <div class="secondary-info">
    <h1 id="edit-a-video"> <%= t('reupload_video') + video.position.to_s %> </h1>
    <div id="filesize">
      <p><%= t('note_max_video_size_50m') %></p>
      <p><%= t('supported_video_format') %></p>
    </div>
    <a class= "fileupload-btn button">
      <span id="upload-tip"><%= t('click_to_upload_a_video') %></span>
      <input id="fileupload" name="video[asset]" type="file">
    </a>
    <script id="template-upload" type="text/x-tmpl">
      <div class="upload">
        {%=o.name%}
        <div class="progress"><div class="bar" style="width: 0%"></div></div>
      </div>
    </script>
  </div>

  <div class="primary-info">
    <h1><%= t('enter_video_info') %></h1>
    <%= form_for video do |f| %>
      <dl class="form">
        <dt>
          <%= f.hidden_field :id %>
          <%= f.label t("video_title") %>
        </dt>
        <dd>
        <%= f.text_field :title, :class => "short" %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
        <%= f.label t("video_desc") %>
        </dt>
        <dd>
        <%= f.text_area :desc, :id => "video_desc", :class => "short" %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
        <%= f.check_box :free %>
        <%= f.label t('free') %>
        </dt>
      </dl>
      <p>
        <%= f.submit t('save'), :class => "minibutton", data: {disable_with: t('saving') + "..."},:id => "submit_video_info" %>
        <%= link_to t('cancel'), edit_course_path(video.course), :class => "minibutton"%>
      </p>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<% content_for :template_js do %>
  <script>
    $('#course_desc').NobleCount('#desc_count',{
      on_negative: 'go_red',
      on_positive: 'go_green',
      max_chars: 33});
  </script>
<% end %>
<%= form_for(@course, :url => "/course") do |f| %>
  <%= f.hidden_field :user_id %>
  <%= flash[:notice] %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <dl class="form">
    <dt> <%= f.label t('course_title') %> </dt>
    <dd> <%= f.text_field :title %> </dd>
  </dl>
  

  <div>
    <%= f.submit t('create_course'), :class => "minibutton primary" %>
  </div>
<% end %>

app/views/courses/_update_form.html.erb
<% content_for :template_js do %>
  <script>
    $('#course_desc').NobleCount('#desc_count',{
      on_negative: 'go_red',
      on_positive: 'go_green',
      max_chars: 33});
  </script>
<% end %>
<%= form_for(@course, :url => "/course") do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :name %>
  <%= flash[:notice] %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <dl class="form">
    <dt> <%= f.label :price %> </dt>
    <dd> <%= f.text_field :price, :class => "short" %> </dd>
  </dl>
  <dl class="form">
    <dt> <%= f.label :title %> </dt>
    <dd> <%= f.text_field :title, :class => "short"  %> </dd>
  </dl>
  <dl class="form">
    <dt>
      <%= f.label :description %>
      (<%= t('remaining') %><span id='desc_count'></span> <%= t('characters') %>)
    </dt>
    <dd>
      <%= f.text_area :description, :size => "14x4", :id => "course_desc" %>
    </dd>
  </dl>
  <div class="form">
    <%= f.check_box :public %>
    <%= f.label t('public') %>
  </div>
  <div>
    <%= f.submit t('update_course'), :class => "button primary" %>
    <span id="edit-course-delete">
      <%= link_to t('delete_this_course'), @course, :confirm => t('confirm_delete'), :method => :delete, :class => "minibutton danger" %>
    </span>
  </div>
<% end %>

app/views/courses/edit.html.erb
<% content_for :template_js do %>
  <%= javascript_include_tag 'i_fileupload'%>
  <script>
    jQuery(function($) {
      var _tip = $("#poster-upload-tip");
      $('#poster-fileupload').fileupload({
          dataType: 'script',
          url: '/update_poster/<%= @course.id %>',
          add: function(e, data){
            types = /(\.|\/)(gif|jpe?g|png)$/i;
            file = data.files[0];
            if (types.test(file.type) || types.test(file.name))
            {
              data.submit();
            }
            else
            {
              alert(file.name + " 不是图片，请重新选择！");
            }
          },
          start: function(e) {
            _tip.html('上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
            _tip.html("课程封面修改成功!");
          },
      });
      $("#course_title").keyup(function(){
        document.all["input_title2"].value = document.all["course_title"].value;
      });
      $("#course_desc").keyup(function(){
        document.all["input_content2"].value = document.all["course_desc"].value;
      });
    
  });
  </script>
<% end %>
<div class='container'>
  <div class="tutorial-page">
    <div class="tutorial-nav">
      <h3>
        <%= @course.title %>
        <%= link_to t('go_back'), @course, :class => "button" %>
      </h3>
      <% if @course.videos %>
        <%= render "all_added_videos", :course => @course %>
      <% end %>
      <div class="edit-course-info-area">
        <div id="edit-course-poster">
          <p><%= t('course_poster') %>(<%= t('course_poster_dimension') %>)</p>
          <a class= "fileupload-btn button primary">
            <span id="poster-upload-tip"><%= t('change_poster') %></span>
            <input id="poster-fileupload" name="course[poster]" type="file">
          </a>
        </div>
        <div id="edit-course-desc">
          <%= render 'update_form', :course => @course %>
        </div>
      </div>
    </div>
    <div class="tutorial-content">
      <%= render "add_photo", :course => @course %>
    </div>
  </div>
</div>

app/views/courses/edit_video.js.erb
$('.add-video-box').replaceWith("<%= escape_javascript render 'edit_video', :video => @video %>");
$('.playlist li a.video').removeClass('active');
$('.playlist li a.video').eq(<%= @video.position - 1 %>).addClass('active');

app/views/courses/new.html.erb
<div class="single-form-container">

  <div class="boxed-group">
    <h3><%= t('create_course') %></h3>
    <div class="boxed-group-inner">
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/courses/show.html.erb
<div class="pagehead clearfix">
  <div class="container">
    <ul class="pagehead-actions">
      <% if @course.user == current_user %>
        <li>
        <%= link_to t('edit_course'), edit_course_path(@course), class: "minibutton" %>
        </li>
      <% end %>
      <% if not @course.open_to_user?(current_user) %>
        <li>
        <%= link_to t('buy_this_course') + "（￥" + @course.price.to_s + "）", new_order_path + "?course_id=#{@course.id}", class: "minibutton primary" %>
        </li>
      <% end %>
      <li>
      <%= course_watch_tag(@course) %>
      <% if owner?(@course) %>
        <%= link_to "关注人数", course_watchers_path, :class => "social-count-title" %>
      <% end %>
      <%= link_to @course.watchers.count, course_watchers_path, :class => "social-count" %>
      </li>
    </ul>
    <h1 class="pagehead-heading">
      <div class="course-image" style="background-image: url(<%= @course.poster_url %>);"> </div>
      <span class="author">
        <%= link_to @course.user.name, member_path(@course.user.name), class: "author"%>
      </span>
      <span class="pagehead-name-divider">/</span>
      <strong><%= link_to @course.title, course_path(@course) %></strong>
    </h1>
    <br>
    <p class="course-desc"><%= auto_link @course.description %></p>
  </div>
</div>
<div class='container'>
  <% if not @video %>
    <h1><%= @course.title %></h1>
    <div class="alert">
      <%= t('no_classes') %>
      <% if @course.user == current_user %>
        <%= link_to t('edit_course'), edit_course_path(@course), class: "minibutton" %>
        <%= link_to t('delete_this_course'), @course, :confirm => t('confirm_delete'), :method => :delete, :class => "minibutton" %>
      <% end %>
    </div>
  <% else %>

    <div class="tutorial-page">
      <div class="tutorial-nav">
        <%= render "play_list", :course => @course, :current_video => @video %>
        <div class="course-update-time">
          <i class="icon-time"></i>
          <span><%= t('update_time') %></span>
          <span><%= link_to @course.updated_at.strftime(t('date.formats.default')), timeline_course_path %></span>
        </div>
      </div>
      <div class="tutorial-content">
        <%= render "video_info", :video => @video %>
        <% if @course.open_to_user?(current_user) || @video.open_to_user?(current_user) %>
          <%= render "video_player", :video => @video %>
        <% else %>
          <%= link_to t('pay_for_course_please'), new_order_path + "?course_id=#{@course.id}", class: "button primary" %>
        <% end %>
        <div id="comments">
          <h3><%= t("comment") %></h3>
          <%= render @video.comments %>
        </div>
        <% if current_user %>
          <%= render "comments/new_comment_form" %>
        <% else %>
          <div id="login_buttons">
            <%= link_to t("login_and_comment"), login_path(:return_to => request.url) ,:class => "btn btn-success" %>
          </div>
          <br \>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% content_for :template_js do %>
  <script>
    $("textarea#comment_content").keydown(function(e) {
      if (e.ctrlKey && e.keyCode == 13) {
        $("input[type=submit]").click();
      }
    });
  </script>
<% end %>

app/views/courses/update_poster.js.erb
$('img#poster').replaceWith('<%= image_tag @course.poster_url,:alt => "Poster Image", :id => "poster"%>');

app/views/courses/watchers.html.erb
<div class="container">
  <div id="watcher-page">
    <div class="title">
      <%= t 'watchers' %> <%= @watchers.count %>
    </div>
    <% if @watchers.blank? %>
      <%= t 'no_watcher_found' %>
    <% else %>
      <%= render :partial => "shared/member_list", :locals => {:members => @watchers} %>
    <% end %>
  </div>
</div>